import { Product } from './types';

export const products: Product[] = [
  {
    id: 'pantene-shampoo',
    name: 'Pro-V Daily Moisture Renewal Shampoo',
    brand: 'Pantene',
    category: 'Haircare',
    size: '50ml',
    price: 49,
    description: 'Nourishing shampoo for daily moisture',
  },
  {
    id: 'tresemme-shampoo',
    name: 'Keratin Smooth Shampoo',
    brand: 'TRESemmé',
    category: 'Haircare',
    size: '50ml',
    price: 59,
    description: 'Professional-quality keratin smoothing shampoo',
  },
  {
    id: 'nivea-body-lotion',
    name: 'Express Body Lotion',
    brand: 'Nivea',
    category: 'Skincare',
    size: '75ml',
    price: 45,
    description: 'Fast-absorbing moisturizing body lotion',
  },
  {
    id: 'dove-body-wash',
    name: 'Deep Moisture Body Wash',
    brand: 'Dove',
    category: 'Hygiene',
    size: '50ml',
    price: 39,
    description: 'Gentle cleansing with moisturizing cream',
  },
  {
    id: 'colgate-toothpaste',
    name: 'Total Original Toothpaste',
    brand: 'Colgate',
    category: 'Hygiene',
    size: '20ml',
    price: 25,
    description: 'Complete protection for teeth and gums',
  },
  {
    id: 'laroche-sunscreen',
    name: 'Anthelios UV Mune SPF50+',
    brand: 'La Roche-Posay',
    category: 'Skincare',
    size: '50ml',
    price: 129,
    description: 'Very high protection sunscreen',
  },
  {
    id: 'nivea-sun',
    name: 'Sun Protect & Moisture SPF30',
    brand: 'Nivea Sun',
    category: 'Skincare',
    size: '50ml',
    price: 69,
    description: 'Water-resistant sun protection',
  },
  {
    id: 'burtsbees-lip',
    name: 'Beeswax Lip Balm',
    brand: "Burt's Bees",
    category: 'Skincare',
    size: '4.25g',
    price: 59,
    description: '100% natural moisturizing lip balm',
  },
  {
    id: 'loccitane-hand',
    name: 'Shea Butter Hand Cream',
    brand: "L'Occitane",
    category: 'Skincare',
    size: '30ml',
    price: 99,
    description: 'Intensive hand moisturizer',
  },
  {
    id: 'neutrogena-hand',
    name: 'Norwegian Formula Hand Cream',
    brand: 'Neutrogena',
    category: 'Skincare',
    size: '50ml',
    price: 65,
    description: 'Clinically proven hand relief',
  },
  {
    id: 'dove-deodorant',
    name: 'Original Deodorant Roll-On',
    brand: 'Dove',
    category: 'Hygiene',
    size: '50ml',
    price: 35,
    description: '48-hour protection with moisturizers',
  },
  {
    id: 'sensodyne-toothpaste',
    name: 'Sensitive Repair Toothpaste',
    brand: 'Sensodyne',
    category: 'Hygiene',
    size: '20ml',
    price: 29,
    description: 'Clinically proven sensitivity relief',
  },
  {
    id: 'rituals-shower',
    name: 'The Ritual of Sakura Shower Gel',
    brand: 'Rituals',
    category: 'Hygiene',
    size: '50ml',
    price: 79,
    description: 'Refreshing cherry blossom shower gel',
  },
  {
    id: 'bioderma-micellar',
    name: 'Micellar Water',
    brand: 'Bioderma Sensibio',
    category: 'Skincare',
    size: '100ml',
    price: 89,
    description: 'Gentle makeup remover and cleanser',
  },
  {
    id: 'batiste-dry-shampoo',
    name: 'Dry Shampoo Fresh',
    brand: 'Batiste',
    category: 'Haircare',
    size: '50ml',
    price: 49,
    description: 'Instant refresh between washes',
  },
  {
    id: 'nivea-after-sun',
    name: 'After Sun Moisturizing Lotion',
    brand: 'Nivea Sun',
    category: 'Skincare',
    size: '100ml',
    price: 59,
    description: 'Soothing after-sun care',
  },
  {
    id: 'nivea-men-deo',
    name: 'Men Sensitive Deodorant',
    brand: 'Nivea Men',
    category: 'Hygiene',
    size: '50ml',
    price: 39,
    description: 'Gentle protection for sensitive skin',
  },
  {
    id: 'moroccanoil-treatment',
    name: 'Argan Oil Hair Treatment',
    brand: 'Moroccanoil',
    category: 'Haircare',
    size: '25ml',
    price: 149,
    description: 'Nourishing argan oil formula',
  },
  {
    id: 'dove-beauty-bar',
    name: 'Beauty Bar Travel Size',
    brand: 'Dove',
    category: 'Hygiene',
    size: '50g',
    price: 29,
    description: 'Gentle cleansing bar with moisturizing cream',
  },
  {
    id: 'labello-lip',
    name: 'Classic Care Lip Balm',
    brand: 'Labello',
    category: 'Skincare',
    size: '4.8g',
    price: 35,
    description: 'Long-lasting lip care with vitamin E',
  },
];
