import { Product } from './types';

export const products: Product[] = [
  {
    id: 'pantene-shampoo',
    name: 'Pro-V Daily Moisture Renewal Shampoo',
    brand: 'Pantene',
    category: 'Haircare',
    size: '50ml',
    price: 49,
    description: 'Nourishing shampoo for daily moisture',
    sku: 'TE-HC-PAN-001',
    slug: 'pantene-pro-v-daily-moisture-shampoo-50ml',
    shortDescription: 'Nourishing shampoo for daily moisture',
    status: 'active',
    featured: true,
    stock: 75,
    compareAtPrice: 59,
  },
  {
    id: 'tresemme-shampoo',
    name: 'Keratin Smooth Shampoo',
    brand: 'TRESemmé',
    category: 'Haircare',
    size: '50ml',
    price: 59,
    description: 'Professional-quality keratin smoothing shampoo',
    sku: 'TE-HC-TRE-001',
    slug: 'tresemme-keratin-smooth-shampoo-50ml',
    shortDescription: 'Professional-quality keratin smoothing',
    status: 'active',
    featured: true,
    stock: 60,
  },
  {
    id: 'nivea-body-lotion',
    name: 'Express Body Lotion',
    brand: 'Nivea',
    category: 'Skincare',
    size: '75ml',
    price: 45,
    description: 'Fast-absorbing moisturizing body lotion',
    sku: 'TE-SC-NIV-001',
    slug: 'nivea-express-body-lotion-75ml',
    shortDescription: 'Fast-absorbing moisturizing lotion',
    status: 'active',
    featured: true,
    stock: 85,
  },
  {
    id: 'dove-body-wash',
    name: 'Deep Moisture Body Wash',
    brand: 'Dove',
    category: 'Hygiene',
    size: '50ml',
    price: 39,
    description: 'Gentle cleansing with moisturizing cream',
    sku: 'TE-HY-DOV-001',
    slug: 'dove-deep-moisture-body-wash-50ml',
    shortDescription: 'Gentle cleansing with moisturizing cream',
    status: 'active',
    featured: false,
    stock: 90,
  },
  {
    id: 'colgate-toothpaste',
    name: 'Total Original Toothpaste',
    brand: 'Colgate',
    category: 'Hygiene',
    size: '20ml',
    price: 25,
    description: 'Complete protection for teeth and gums',
    sku: 'TE-HY-COL-001',
    slug: 'colgate-total-original-toothpaste-20ml',
    shortDescription: 'Complete protection for teeth and gums',
    status: 'active',
    featured: false,
    stock: 120,
  },
  {
    id: 'laroche-sunscreen',
    name: 'Anthelios UV Mune SPF50+',
    brand: 'La Roche-Posay',
    category: 'Skincare',
    size: '50ml',
    price: 129,
    description: 'Very high protection sunscreen',
    sku: 'TE-SC-LRP-001',
    slug: 'la-roche-posay-anthelios-uv-mune-spf50-50ml',
    shortDescription: 'Very high protection sunscreen',
    status: 'active',
    featured: true,
    stock: 40,
    compareAtPrice: 149,
  },
  {
    id: 'nivea-sun',
    name: 'Sun Protect & Moisture SPF30',
    brand: 'Nivea Sun',
    category: 'Skincare',
    size: '50ml',
    price: 69,
    description: 'Water-resistant sun protection',
    sku: 'TE-SC-NIV-002',
    slug: 'nivea-sun-protect-moisture-spf30-50ml',
    shortDescription: 'Water-resistant sun protection',
    status: 'active',
    featured: true,
    stock: 70,
  },
  {
    id: 'burtsbees-lip',
    name: 'Beeswax Lip Balm',
    brand: "Burt's Bees",
    category: 'Skincare',
    size: '4.25g',
    price: 59,
    description: '100% natural moisturizing lip balm',
    sku: 'TE-SC-BUR-001',
    slug: 'burts-bees-beeswax-lip-balm-4g',
    shortDescription: '100% natural moisturizing lip balm',
    status: 'active',
    featured: false,
    stock: 100,
  },
  {
    id: 'loccitane-hand',
    name: 'Shea Butter Hand Cream',
    brand: "L'Occitane",
    category: 'Skincare',
    size: '30ml',
    price: 99,
    description: 'Intensive hand moisturizer',
    sku: 'TE-SC-LOC-001',
    slug: 'loccitane-shea-butter-hand-cream-30ml',
    shortDescription: 'Intensive hand moisturizer',
    status: 'active',
    featured: true,
    stock: 55,
  },
  {
    id: 'neutrogena-hand',
    name: 'Norwegian Formula Hand Cream',
    brand: 'Neutrogena',
    category: 'Skincare',
    size: '50ml',
    price: 65,
    description: 'Clinically proven hand relief',
    sku: 'TE-SC-NEU-001',
    slug: 'neutrogena-norwegian-formula-hand-cream-50ml',
    shortDescription: 'Clinically proven hand relief',
    status: 'active',
    featured: false,
    stock: 65,
  },
  {
    id: 'dove-deodorant',
    name: 'Original Deodorant Roll-On',
    brand: 'Dove',
    category: 'Hygiene',
    size: '50ml',
    price: 35,
    description: '48-hour protection with moisturizers',
    sku: 'TE-HY-DOV-002',
    slug: 'dove-original-deodorant-roll-on-50ml',
    shortDescription: '48-hour protection with moisturizers',
    status: 'active',
    featured: false,
    stock: 90,
  },
  {
    id: 'sensodyne-toothpaste',
    name: 'Sensitive Repair Toothpaste',
    brand: 'Sensodyne',
    category: 'Hygiene',
    size: '20ml',
    price: 29,
    description: 'Clinically proven sensitivity relief',
    sku: 'TE-HY-SEN-001',
    slug: 'sensodyne-sensitive-repair-toothpaste-20ml',
    shortDescription: 'Clinically proven sensitivity relief',
    status: 'active',
    featured: false,
    stock: 110,
  },
  {
    id: 'rituals-shower',
    name: 'The Ritual of Sakura Shower Gel',
    brand: 'Rituals',
    category: 'Hygiene',
    size: '50ml',
    price: 79,
    description: 'Refreshing cherry blossom shower gel',
    sku: 'TE-HY-RIT-001',
    slug: 'rituals-sakura-shower-gel-50ml',
    shortDescription: 'Refreshing cherry blossom shower gel',
    status: 'active',
    featured: true,
    stock: 50,
  },
  {
    id: 'bioderma-micellar',
    name: 'Micellar Water',
    brand: 'Bioderma Sensibio',
    category: 'Skincare',
    size: '100ml',
    price: 89,
    description: 'Gentle makeup remover and cleanser',
    sku: 'TE-SC-BIO-001',
    slug: 'bioderma-sensibio-micellar-water-100ml',
    shortDescription: 'Gentle makeup remover and cleanser',
    status: 'active',
    featured: false,
    stock: 60,
  },
  {
    id: 'batiste-dry-shampoo',
    name: 'Dry Shampoo Fresh',
    brand: 'Batiste',
    category: 'Haircare',
    size: '50ml',
    price: 49,
    description: 'Instant refresh between washes',
    sku: 'TE-HC-BAT-001',
    slug: 'batiste-dry-shampoo-fresh-50ml',
    shortDescription: 'Instant refresh between washes',
    status: 'active',
    featured: false,
    stock: 45,
  },
  {
    id: 'nivea-after-sun',
    name: 'After Sun Moisturizing Lotion',
    brand: 'Nivea Sun',
    category: 'Skincare',
    size: '100ml',
    price: 59,
    description: 'Soothing after-sun care',
    sku: 'TE-SC-NIV-003',
    slug: 'nivea-after-sun-moisturizing-lotion-100ml',
    shortDescription: 'Soothing after-sun care',
    status: 'active',
    featured: false,
    stock: 55,
  },
  {
    id: 'nivea-men-deo',
    name: 'Men Sensitive Deodorant',
    brand: 'Nivea Men',
    category: 'Hygiene',
    size: '50ml',
    price: 39,
    description: 'Gentle protection for sensitive skin',
    sku: 'TE-HY-NIV-001',
    slug: 'nivea-men-sensitive-deodorant-50ml',
    shortDescription: 'Gentle protection for sensitive skin',
    status: 'active',
    featured: false,
    stock: 75,
  },
  {
    id: 'moroccanoil-treatment',
    name: 'Argan Oil Hair Treatment',
    brand: 'Moroccanoil',
    category: 'Haircare',
    size: '25ml',
    price: 149,
    description: 'Nourishing argan oil formula',
    sku: 'TE-HC-MOR-001',
    slug: 'moroccanoil-argan-oil-hair-treatment-25ml',
    shortDescription: 'Nourishing argan oil formula',
    status: 'active',
    featured: true,
    stock: 30,
    compareAtPrice: 169,
  },
  {
    id: 'dove-beauty-bar',
    name: 'Beauty Bar Travel Size',
    brand: 'Dove',
    category: 'Hygiene',
    size: '50g',
    price: 29,
    description: 'Gentle cleansing bar with moisturizing cream',
    sku: 'TE-HY-DOV-003',
    slug: 'dove-beauty-bar-travel-size-50g',
    shortDescription: 'Gentle cleansing bar with moisturizing cream',
    status: 'active',
    featured: false,
    stock: 95,
  },
  {
    id: 'labello-lip',
    name: 'Classic Care Lip Balm',
    brand: 'Labello',
    category: 'Skincare',
    size: '4.8g',
    price: 35,
    description: 'Long-lasting lip care with vitamin E',
    sku: 'TE-SC-LAB-001',
    slug: 'labello-classic-care-lip-balm-5g',
    shortDescription: 'Long-lasting lip care with vitamin E',
    status: 'active',
    featured: false,
    stock: 100,
  },
];
